name: Run Tests

on:
  push:
    branches-ignore:
      - main # Exclude the main branch if you only want to run this on other branches
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Or whatever version you want to specify

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
